### ISSUE TITLE
Unable to kill emacs

### ISSUE THREAD

**Issue by mtreca** [nicolaisingh/saveplace-pdf-view#8] opened 2021-07-20 10:48 UTC
This issue is very similar to the one mentioned in #2, but I get a different error message and backtrace:

```elisp
Debugger entered--Lisp error: (wrong-type-argument listp t)
  image-mode-winprops(nil)
  image-mode-window-get(page nil)
  pdf-view-bookmark-make-record()
  saveplace-pdf-view-to-alist(pdf-view-bookmark pdf-view-bookmark-make-record)
  saveplace-pdf-view-to-alist-advice(#f(compiled-function () #<bytecode 0x458ad843>))
  apply(saveplace-pdf-view-to-alist-advice #f(compiled-function () #<bytecode 0x458ad843>) nil)
  save-place-to-alist()
  save-places-to-alist()
  save-place-kill-emacs-hook()
  kill-emacs()
  save-buffers-kill-emacs(nil)
  save-buffers-kill-terminal(nil)
  funcall-interactively(save-buffers-kill-terminal nil)
  call-interactively(save-buffers-kill-terminal nil nil)
  command-execute(save-buffers-kill-terminal)
```

I am on Emacs-mac 27.2. I will try to get a minimal way to reproduce the issue at some point.

**Comment by nicolaisingh** [comment] 2021-07-21 07:27
hi, so far I'm not able to reproduce this issue.  does this occur 100% of the time?  and I'm assuming this happens when exiting emacs?

i'm not yet sure, but the problem might be in `pdf-view` or `image-mode` based on the trace above.

**Comment by mtreca** [comment] 2021-07-28 13:21
It does occur rarely, and the issue is that I am not sure what triggers it exactly. My hint is that it has to do with broken or invalid PDFs since I tend to generate quite a lot of those within Emacs. I will post a recipe to recreate this issue if I ever manage to isolate it.

**Comment by nicolaisingh** [comment] 2023-06-24 12:36
Closing.

**Closed as completed by nicolaisingh** 2023-06-24 12:36 UTC
